version: "2"

run:
  tests: false

linters:
  enable:
    # Minimum essential linters
    - errcheck
    - govet
    - staticcheck

    # Additional useful linters (uncomment if needed)
    # - gosimple
    # - ineffassign
    # - unused
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - contextcheck
    # - durationcheck
    # - errchkjson
    # - errorlint
    # - exhaustive
    # - gocheckcompilerdirectives
    # - gochecksumtype
    # - gosec
    # - gosmopolitan
    # - loggercheck
    # - makezero
    # - musttag
    # - nilerr
    # - nilnesserr
    # - noctx
    # - protogetter
    # - reassign
    # - recvcheck
    # - rowserrcheck
    # - spancheck
    # - sqlclosecheck
    # - testifylint
    # - unparam
    # - zerologlint

issues:
  new: true
  exclude:
    - G115

# Uncomment if you need exclusions
# linters:
#   exclusions:
#     generated: lax
#     presets:
#       - comments
#       - common-false-positives
#       - legacy
#       - std-error-handling
#     rules:
#       - path: (.+)\.go$
#         text: G115
#     paths:
#       - third_party$
#       - builtin$
#       - examples$

# formatters:
#   exclusions:
#     generated: lax
#     paths:
#       - third_party$
#       - builtin$
#       - examples$