// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/Article/article-service/internal/article/domain/entity"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// MockArticleReaderRepository is an autogenerated mock type for the ArticleReaderRepository type
type MockArticleReaderRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: articleId
func (_m *MockArticleReaderRepository) Get(articleId uuid.UUID) (*entity.Article, error) {
	ret := _m.Called(articleId)

	var r0 *entity.Article
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.Article); ok {
		r0 = rf(articleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(articleId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
