// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/Article/article-service/internal/article/domain/entity"
	"github.com/stretchr/testify/mock"
)

// MockArticleWriterRepository is an autogenerated mock type for the ArticleWriterRepository type
type MockArticleWriterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: article
func (_m *MockArticleWriterRepository) Create(article *entity.Article) (*entity.Article, error) {
	ret := _m.Called(article)

	var r0 *entity.Article
	if rf, ok := ret.Get(0).(func(*entity.Article) *entity.Article); ok {
		r0 = rf(article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Article) error); ok {
		r1 = rf(article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
